### ISSUE TITLE
Warning: render(): Rendering

### ISSUE THREAD

**Issue by yoshixmk** [asos-craigmorten/deno-react-base-server#2]
![image](https://user-images.githubusercontent.com/6196702/86527171-5ca84880-bed7-11ea-9dca-47cf9474b99f.png)
I checked it in the local environment using the command below, and localhost:3000.  
```Shell
deno run --allow-net --allow-read "https://raw.githubusercontent.com/asos-craigmorten/deno-react-base-server/main/example/entrypoint.ts"
```
I think [this](https://stackoverflow.com/a/50227839) about the problem. 
> This problem happens if in your index.html the html body tag has root id.

**Comment by asos-craigmorten** [comment]
Thanks for pointing out @yoshixmk will look to remedy.

My preferred approach for React SSR is now available [here](https://github.com/asos-craigmorten/opine/tree/main/examples/react) which I don’t think suffers from this.

**Comment by yoshixmk** [comment]
It’s nice to be able to SSR by opine, Great!
I try it. Thanks!

**Comment by asos-craigmorten** [comment]
Thanks for raising this - I've updated to write to a top-level container element instead of the body.
